[package]
name = "harmony-data"
version = "0.1.0"
authors = ["Daxanius"]
edition = "2021"

[dependencies]
diesel = { version = "2.2", features = ["postgres", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4" }
dotenvy = "0.15"
